
name: zapfull-security-scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
      # To be able to push to the repo
      contents: write
      # To update the PR description with canary info
      pull-requests: write
      # For pr-check to create a status
      statuses: write
      # Needed to create PR statuses/checks
      checks: write
      # To post comments on PRs
      issues: write
      # To create NPM packages in GitHub
      packages: write


jobs:
      zap_scan:
           runs-on: ubuntu-latest
           name: Scan the web application
